version: '3'

services:

  postgres:
   image: postgres
   volumes:
     - data:/var/lib/postgresql/data
     - logspgsql:/var/log/postgresql
   environment:
     POSTGRES_USER: postgres
     POSTGRES_PASSWORD: postgres
   expose:
     - "5432"
   networks:
     - local
  
  api:
    build: ./api/.
    volumes:
      - ./api/apicode:/code
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    networks:
      - local
    depends_on:
      - postgres

    
volumes:
  data:
  logspgsql:

networks:
  local: